### ISSUE TITLE
I get error "undefined method 'add_column'" when trying to perform what appears to be a valid migration

### ISSUE THREAD

**Issue by dscottboggs** [luckyframework/avram#19]
When attempting to migrate 

```crystal
class CreateListAndListEntry::V20180930082950 < LuckyRecord::Migrator::Migration::V1
  def migrate
    create :list_entries do
      add title : String
      add_belongs_to list : List, on_delete: :do_nothing
      add_belongs_to author : User, on_delete: :cascade
    end
    create :lists do
      add title : String
    end
    alter :users do
      add list_entries : ListEntry, fill_existing_with: :nothing
    end
  end

  def rollback
    drop :list_entries
    drop :lists
    alter :users do
      remove :list_entries
    end
  end
end
```

I receive the following error message: [undefined method 'add_column'](https://github.com/dscottboggs/lucky-shopping-list/blob/master/ERROR.txt)

You can find the whole project here https://github.com/dscottboggs/lucky-shopping-list

thanks for the help

**Comment by jwoertink** [comment]
This is an old issue, so I assume it's been fixed by now, but the first issue I saw here was on [this line](https://github.com/dscottboggs/lucky-shopping-list/blob/master/db/migrations/20180930082950_create_list_and_list_entry.cr#L12) where you specify a column type to be `ListEntry`, but since postgres doesn't have a `ListEntry` type, things may get a little funky. We should probably do a supported types deal where this should raise a compile time error.

**Comment by paulcsmith** [comment]
I totally missed this. Yeah looks like it needed to be `add_belongs_to`. We should have some kind of helpful error like you said, where if a type is not resolved it lets people know rather than giving some random error
